/*--------------------------------------------------------------------------------*
  Copyright (C)Nintendo All rights reserved.

  These coded instructions, statements, and computer programs contain proprietary
  information of Nintendo and/or its licensed developers and are protected by
  national and international copyright laws. They may not be disclosed to third
  parties or copied or duplicated in any form, in whole or in part, without the
  prior written consent of Nintendo.

  The content herein is highly confidential and should be handled accordingly.
 *--------------------------------------------------------------------------------*/

#pragma once

#include <nn/nn_Common.h>
#include <utility>

#if 0 // defined(NN_BUILD_CONFIG_COMPILER_USE_VARIADIC_TEMPLATE)

    #define NN_UTIL_VARIADIC_DEFINE_MACROS(macro) macro(VARIADIC)

#else

    #define NN_UTIL_VARIADIC_DEFINE_MACROS(macro) \
        macro(001) \
        macro(002) \
        macro(003) \
        macro(004) \
        macro(005) \
        macro(006) \
        macro(007) \
        macro(008) \
        macro(009) \
        macro(010) \
        macro(011) \
        macro(012) \
        macro(013) \
        macro(014) \
        macro(015) \
        macro(016)

#endif

#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_VARIADIC(T) typename... Args##T
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_001(T)                                                      typename T##001
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_002(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_001(T), typename T##002
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_003(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_002(T), typename T##003
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_004(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_003(T), typename T##004
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_005(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_004(T), typename T##005
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_006(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_005(T), typename T##006
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_007(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_006(T), typename T##007
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_008(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_007(T), typename T##008
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_009(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_008(T), typename T##009
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_010(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_009(T), typename T##010
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_011(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_010(T), typename T##011
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_012(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_011(T), typename T##012
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_013(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_012(T), typename T##013
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_014(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_013(T), typename T##014
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_015(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_014(T), typename T##015
#define NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_016(T) NN_UTIL_VARIADIC_TEMPLATE_TEMPLATE_ARGUMENTS_015(T), typename T##016

#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_VARIADIC(T, args) Args##T&&... args
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_001(T, x)                                                    T##001&& x##001
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_002(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_001(T, x), T##002&& x##002
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_003(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_002(T, x), T##003&& x##003
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_004(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_003(T, x), T##004&& x##004
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_005(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_004(T, x), T##005&& x##005
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_006(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_005(T, x), T##006&& x##006
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_007(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_006(T, x), T##007&& x##007
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_008(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_007(T, x), T##008&& x##008
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_009(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_008(T, x), T##009&& x##009
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_010(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_009(T, x), T##010&& x##010
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_011(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_010(T, x), T##011&& x##011
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_012(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_011(T, x), T##012&& x##012
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_013(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_012(T, x), T##013&& x##013
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_014(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_013(T, x), T##014&& x##014
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_015(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_014(T, x), T##015&& x##015
#define NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_016(T, x) NN_UTIL_VARIADIC_TEMPLATE_ARGUMENT_LIST_015(T, x), T##016&& x##016

#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_VARIADIC(T, args) ::std::forward<Args##T>(args)...
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_001(T, x)                                                   ::std::forward<T##001>(x##001)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_002(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_001(T, x), ::std::forward<T##002>(x##002)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_003(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_002(T, x), ::std::forward<T##003>(x##003)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_004(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_003(T, x), ::std::forward<T##004>(x##004)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_005(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_004(T, x), ::std::forward<T##005>(x##005)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_006(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_005(T, x), ::std::forward<T##006>(x##006)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_007(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_006(T, x), ::std::forward<T##007>(x##007)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_008(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_007(T, x), ::std::forward<T##008>(x##008)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_009(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_008(T, x), ::std::forward<T##009>(x##009)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_010(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_009(T, x), ::std::forward<T##010>(x##010)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_011(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_010(T, x), ::std::forward<T##011>(x##011)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_012(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_011(T, x), ::std::forward<T##012>(x##012)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_013(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_012(T, x), ::std::forward<T##013>(x##013)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_014(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_013(T, x), ::std::forward<T##014>(x##014)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_015(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_014(T, x), ::std::forward<T##015>(x##015)
#define NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_016(T, x) NN_UTIL_VARIADIC_TEMPLATE_FORWARD_LIST_015(T, x), ::std::forward<T##016>(x##016)
